databases:
  - name: property_app
    databaseName: property_app_1m6q
    user: property_app_1m6q_user

services:
  - type: web
    name: property
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: property_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      